name: Nextcloud File Watcher
version: "1.1.0"
slug: nextcloud_file_watcher
description: Überwacht einen Nextcloud-Ordner und sendet Benachrichtigungen bei neuen Dateien.
startup: services
boot: auto
hassio_api: true
homeassistant_api: true
host_network: true
privileged:
  - NET_ADMIN
options:
  nextcloud_url: "https://nextcloud.example.com"
  username: "dein_benutzername"
  password: "dein_passwort"
  watch_folder: "Briefkasten"
  file_types:
    - ".jpg"
    - ".png"
  interval: 30
  notify_service: "notify.mobile_app_dein_gerät"
  enable_contact_lookup: false
schema:
  nextcloud_url: str
  username: str
  password: password
  watch_folder: str
  file_types: list(str)
  interval: int
  notify_service: str
  enable_contact_lookup: bool
