name: Nextcloud File Watcher
version: "1.1.4"
slug: nextcloud_file_watcher
description: Überwacht einen Nextcloud-Ordner und sendet Benachrichtigungen bei neuen Dateien.
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
homeassistant: true
host_network: true
privileged: false
icon: "icon.png"
capabilities:
  - NET_ADMIN
options:
  nextcloud_url: "https://nextcloud.example.com"
  username: "dein_benutzername"
  password: "dein_passwort"
  watch_folder: "Briefkasten"
  file_types:
    - ".jpg"
    - ".png"
  interval: 30
  notify_service: "notify.mobile_app_dein_gerät"
  enable_contact_lookup: false
schema:
  nextcloud_url:
    type: string
  username:
    type: string
  password:
    type: string
  watch_folder:
    type: string
  file_types:
    type: array
    items:
      type: string
  interval:
    type: integer
  notify_service:
    type: string
  enable_contact_lookup:
    type: boolean
