nextcloud_url: "https://deine-nextcloud.example.com"
username: "dein-benutzer"
password: "dein-passwort"
watch_folder: "Briefkasten"
interval: 600
file_types:
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".pdf"
notify_service: "notify.mobile_app_dein_gerät"
enable_contact_lookup: false
