name: Nextcloud File Watcher
version: "0.1.3"
slug: nextcloud_file_watcher
description: Überwacht einen Nextcloud-Ordner und sendet Benachrichtigungen bei neuen Dateien.
startup: application
boot: auto
options:
  enable_contact_lookup: false
  interval: 30
  file_types: []
  username: ""
  password: ""
  notify_service: ""
  nextcloud_url: ""
  watch_folder: ""
schema:
  enable_contact_lookup: bool
  interval: int
  file_types: list(str)
  username: str
  password: password
  notify_service: str
  nextcloud_url: str
  watch_folder: str
image: ghcr.io/electronicresearch/nextcloud-file-watcher-{arch}
